# Generated by Django 4.0.2 on 2022-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avatar.png', null=True, upload_to=''),
        ),
    ]
